# -*- coding: utf-8 -*-
"""Pandas_usingRankforvalues.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAXTWuYYsp1TOFpY6zfxsFRtMtaH1dqS
"""

# Example 20: Pandas - Using Rank to Rank Values
import pandas as pd

# Creating a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Score': [85, 90, 78, 92]}
df = pd.DataFrame(data)

# Ranking scores in descending order
df['Rank'] = df['Score'].rank(ascending=False)

print('DataFrame with Ranked Scores:\n', df)